language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "pypy"

branches:
  only:
    - master

install:
  - if [[ $TRAVIS_PYTHON_VERSION == '3.5' ]]; then travis_retry pip install aiohttp; fi
  - travis_retry pip install coveralls
  - travis_retry pip install coverage
  - travis_retry pip install nose
  - travis_retry pip install .

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.pyenv

script:
  - nosetests --with-coverage

after_success:
  - coveralls
