[tool.poetry]
name = "mygeotab"
version = "0.8.5"
description = "An unofficial Python client for the MyGeotab API"
authors = ["Aaron Toth"]
license = "Apache-2.0"
readme = "README.rst"
homepage = "https://github.com/geotab/mygeotab-python"
repository = "https://github.com/geotab/mygeotab-python"
documentation = "https://mygeotab-python.readthedocs.io"
classifiers=[
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Natural Language :: English",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 2.7",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.4",
    "Programming Language :: Python :: 3.5",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: Implementation :: PyPy",
    "Topic :: Software Development :: Libraries",
]

[tool.poetry.dependencies]
python = ">=2.7.9 >=3.5"
click = "^7.0"
pytz = "^2019.3"
arrow = "^0.15.4"
six = "^1.13.0"

[tool.poetry.dev-dependencies]
pytest = "*"
flake8 = "*"
pytest-cov = "*"
rope = "*"
requests-mock = "*"
pytest-datadir = "*"
pytest-benchmark = "*"
mypy = {version = "*", python = ">=3.5"}
pytest-asyncio = {version = "*", python = ">=3.5"}
black = {version = "*", python = ">=3.6"}

[tool.black]
line-length = 120
target_version = ['py27']
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | build
    | dist
    | docs
  )/
  | foo.py           # also separately exclude a file named foo.py in
                     # the root of the project
)
'''

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"